name: 'Dependabot for Clojure projects'
author: 'Luigi Gubello'
description: 'Run Dependabot as GitHub Action workflow in your Clojure project.'
branding:
  icon: 'shield'
  color: 'gray-dark'
inputs:
  auto_pull_request:
    description: 'Create auto pull-requests when updates for primary dependencies are available.'
    required: false
    default: true
  labels:
    description: 'Add labels to the pull-requests. Separate items by comma.'
    required: false
    default: ""
  reviewers:
    description: 'Add reviewers to the pull-requests. Separate items by comma.'
    required: false
    default: ""
  directory:
    description: 'Directory which will be scanned.'
    required: false
    default: ""
runs:
  using: 'docker'
  image: 'Dockerfile'
